development:
  sessions:
    default:
      database: intranet_development
      hosts:
        - localhost:27017
      options:
  options:

production: 
  sessions:
    default:
      database: intranet_production
      hosts:
        - localhost:27017
      options:
  options:  

test:
  sessions:
    default:
      database: intranet_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
